owner: jc4k7cybf4-ui
repo: status

sites:
  - name: MaxyService App
    url: https://app.maxyservice.com
    maxResponseTime: 5000
  - name: MaxyService Website
    url: https://maxyservice.com
    maxResponseTime: 5000
  - name: MaxyService API
    url: https://app.maxyservice.com/api/health
    expectedStatusCodes:
      - 200
  - name: Supabase Database
    url: https://app.maxyservice.com/api/heartbeat
    method: POST
    expectedStatusCodes:
      - 200
      - 401

assignees:
  - jc4k7cybf4-ui

status-website:
  cname: status.maxyservice.com
  logoUrl: https://maxyservice.com/icon-192x192.png
  favicon: https://maxyservice.com/favicon.ico
  name: MaxyService Status
  introTitle: "**MaxyService** System Status"
  introMessage: Real-time status monitoring for all MaxyService services. If you're experiencing issues, check here first.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: MaxyService
      href: https://maxyservice.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: All Systems Operational
  incidentReport: Incident Report
  liveStatus: Live Status
  overallUptime: Overall Uptime
  responseTime: Response Time
